@RestAssuredTest
Feature: Rest Assured Automation Scenario

  Scenario Outline: API TEST CASE <Test>
    When I TEST REST API TEST: '<Test>'

    Examples:
      | Test                                         |
      | GetAllusers                                  |
      | createEngineeringFlow                        |
      | updateuserprofile                            |
      | GetRulesCatalogueDetails                     |
      | GetAllFolders                                |
      | GetProjectLevelStatistics                    |
      | ReadBusinessGlossary                         |
      | GetAuditEvents                               |
      | ReadBusinessGlossarySankeyAttributes         |
      | GetCleanseRunHistory                         |
      | ReadDataDictionary                           |
      | GetUserInvoiceDetails                        |
      | ReadFileMetadataAndSubUsersForDataDictionary |
      | GetFileDetailsForRedash                      |
      | GetDataForEventInPreviewMode                 |
      | GetUserCardInfo                              |
      | GetParentEngineeringFlows                    |
      | GetUserLoginInfo                             |
      | GetAllEngineeringFlows                       |
      | GetUsers                                     |
      | GetUserPlanDetails                           |
      | GetCleanseJobStatus                          |
      | GetProjectSubscriptionPlanDetails            |
      | GetAllJobsDetails                            |
      | GetProjectsSubscription                      |
      | GetProjectNotificationDetails                |
      | GetProjectUsers                              |
      | GetUserNotificationDetails                   |
      | GetProjectsInfoUsingProjectIDUserID          |
      | GetAllNotifications                          |
      | GetUserDetails                               |
      | GetFileDetailsForRedash                      |
      | Health                                       |
      | GetFileDetailsForProject                     |
      | GetSupportedDBTypes                          |
      | GetFileDetailsForCleanse                     |
      | ReadDataDictionary                           |
      | GetFolderDetailsForCleanse                   |
      | AnalyzeFileContents                          |
      | GetCleanseFolderDetails                      |
      | ListFilesColumnsInformation                  |
      | GetUserPaymentDetails                        |
      | GetEngineeringFlowEventsStatus               |
      | GetFileForDataProfile                        |
      | GetEMRMetrics                                |
      | GetColumnValueFrequency                      |
      | GetFilesListToTriggerTheAutorun              |
      | GetFileForDataQuality                        |
      | GetGraphContents                             |
      | GetInvalidColumnValues                       |
      | SaveBusinessGloassary                        |
      | GetFileContents                              |
      | UpdateBusinessGlossary                       |
      | GetFileDelta                                 |
      | CreateFolders                                |
      | GetFileData                                  |
      | UpdateFolder                                 |
      | GetRules                                     |
      | SaveDataDictionary                           |
      | RunJob                                       |
      | UpdateDataDictonary                          |
      | DownloadFile                                 |
      | GetBucketName                                |
      | GetUserDetails                               |
      | GetFileDetails                               |
      | ApplyRules                                   |
      | SaveCardDetails                              |
      | SaveUserConsent                              |
      | CreateUser                                   |
      | CleanDeactiveProjects                        |
      | Authorisation                                |
      | DeactivateProject                            |
      | ReinstateProject                             |
      | UpdateProject                                |
      | UpdateDataDictionary                         |
      | DeleteUser                                   |
      | RunEngFlow                                   |
      | UpdateEngFlow                                |
      | LivyJoinOperation                            |
      | SaveGraphData                                |
      | DeleteEngFlow                                |
      | UpdateNotificationInactive                   |
      | DeleteEngEventID                             |
      | UpdateRules                                  |
      | DeleteRules                                  |
      | UpdateRulesSequence                          |
      | ChangePassword                               |
      | CreateProject                                |
      | DeleteCleansejob                             |
      | DeleteFile                                   |
      | DeleteFolder                                 |
      | DeleteGlossary                               |
      | DeleteDictionary                             |
      | DeleteProject                                |
      | ListFileContents                             |
      | ProductFeatures                              |
      | GetSubscriptions                             |
      | StripeIntegration                            |
      | StripeWebHookIntegration                     |
      | GetStripeSessionDetails                      |
      | UpdateStripeIntegration                      |
      | RequestPasswordReset                         |
      | UpdateUserPassword                           |
      | ValidatePasswordRequest                      |
      | LivyFileOperation                            |
      | ReadCommonRegexPatterns                      |
      | ReadPredefindedRegexPatterns                 |
      | DownloadDecryptedFile                        |
      | DownloadDecryptedEngFile                     |
      | FetchDataLineageInformation                  |
      | FetchAppStatus                               |
      | FileUploadValidation                         |
      | GetProjectStats - Copy                       |
      | GetProjectStats                              |

